AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

require:
  - rubocop-rails
  - rubocop-rspec

Naming/VariableNumber:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: false
