 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/appearances", type: :request do
  # Appearance. As you add validations to Appearance, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Appearance.create! valid_attributes
      get appearances_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      appearance = Appearance.create! valid_attributes
      get appearance_url(appearance)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_appearance_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      appearance = Appearance.create! valid_attributes
      get edit_appearance_url(appearance)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Appearance" do
        expect {
          post appearances_url, params: { appearance: valid_attributes }
        }.to change(Appearance, :count).by(1)
      end

      it "redirects to the created appearance" do
        post appearances_url, params: { appearance: valid_attributes }
        expect(response).to redirect_to(appearance_url(Appearance.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Appearance" do
        expect {
          post appearances_url, params: { appearance: invalid_attributes }
        }.to change(Appearance, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post appearances_url, params: { appearance: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested appearance" do
        appearance = Appearance.create! valid_attributes
        patch appearance_url(appearance), params: { appearance: new_attributes }
        appearance.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the appearance" do
        appearance = Appearance.create! valid_attributes
        patch appearance_url(appearance), params: { appearance: new_attributes }
        appearance.reload
        expect(response).to redirect_to(appearance_url(appearance))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        appearance = Appearance.create! valid_attributes
        patch appearance_url(appearance), params: { appearance: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested appearance" do
      appearance = Appearance.create! valid_attributes
      expect {
        delete appearance_url(appearance)
      }.to change(Appearance, :count).by(-1)
    end

    it "redirects to the appearances list" do
      appearance = Appearance.create! valid_attributes
      delete appearance_url(appearance)
      expect(response).to redirect_to(appearances_url)
    end
  end
end
