 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/directors", type: :request do
  # Director. As you add validations to Director, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Director.create! valid_attributes
      get directors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      director = Director.create! valid_attributes
      get director_url(director)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_director_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      director = Director.create! valid_attributes
      get edit_director_url(director)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Director" do
        expect {
          post directors_url, params: { director: valid_attributes }
        }.to change(Director, :count).by(1)
      end

      it "redirects to the created director" do
        post directors_url, params: { director: valid_attributes }
        expect(response).to redirect_to(director_url(Director.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Director" do
        expect {
          post directors_url, params: { director: invalid_attributes }
        }.to change(Director, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post directors_url, params: { director: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested director" do
        director = Director.create! valid_attributes
        patch director_url(director), params: { director: new_attributes }
        director.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the director" do
        director = Director.create! valid_attributes
        patch director_url(director), params: { director: new_attributes }
        director.reload
        expect(response).to redirect_to(director_url(director))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        director = Director.create! valid_attributes
        patch director_url(director), params: { director: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested director" do
      director = Director.create! valid_attributes
      expect {
        delete director_url(director)
      }.to change(Director, :count).by(-1)
    end

    it "redirects to the directors list" do
      director = Director.create! valid_attributes
      delete director_url(director)
      expect(response).to redirect_to(directors_url)
    end
  end
end
